#!/bin/bash
#a quick script to test oi on machines with gcc

gcc ../src/oi/* test.c -I../inc -DOI_IPV4 -Wall -pthread -o "test"
gcc ../src/oi/* test.c -I../inc -DOI_IPV6 -Wall -pthread -o "test"
gcc ../src/oi/* test.c -I../inc -DOI_SINGLESTACK -Wall -pthread -o "test"
gcc ../src/oi/* test.c -I../inc -Wall -pthread -o "test"

if [ -f "test" ] ; then

    ./test $@

fi
